// import type { Metadata } from 'next';
// import { Inter } from 'next/font/google';
// import '../globals.css';
// import Navbar from '../components/Navbar';

// const inter = Inter({
// 	variable: '--font-inter',
// 	subsets: ['latin'],
// });

// export const metadata: Metadata = {
// 	title: 'Create Next App',
// 	description: 'Generated by create next app',
// };

// export default function siteLayout({
// 	children,
// }: Readonly<{
// 	children: React.ReactNode;
// }>) {
// 	return (
// 		// <html lang='en'>
// 		// 	<body
// 		// 		className={`${geistSans.variable} ${geistMono.variable} ${inter.variable} antialiased`}
// 		// 	>
// 		// 		{children}
// 		// 	</body>
// 		// </html>
// 		<html lang='en'>
// 			<body className={`${inter.variable} antialiased`}>
// 				<div className='min-h-screen bg-[var(--background)] text-[var(--foreground)]'>
// 					<Navbar />
// 					<div className='mx-auto px-2 md:px-4 xl:px-0 max-w-[1300px]'>
// 						{children}

// 						{/* Footer */}
// 						<div className='mt-10 flex items-center justify-between border-t border-black/5 pt-6 text-xs text-gray-500 mb-6'>
// 							<div className='flex items-center gap-2'>
// 								<span className='grid h-6 w-6 place-items-center rounded bg-[var(--primary)] text-white font-bold'>
// 									I
// 								</span>
// 								<span>
// 									© {new Date().getFullYear()} Enrollait. All rights reserved.
// 								</span>
// 							</div>
// 							<div className='flex items-center gap-6'>
// 								<button className='hover:text-gray-700'>Privacy Policy</button>
// 								<button className='hover:text-gray-700'>
// 									Terms of Service
// 								</button>
// 								<button className='hover:text-gray-700'>Support</button>
// 							</div>
// 						</div>
// 					</div>
// 				</div>
// 			</body>
// 		</html>
// 	);
// }

// app/(site)/layout.tsx
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import Navbar from '../components/Navbar';

const inter = Inter({
	variable: '--font-inter',
	subsets: ['latin'],
});

export const metadata: Metadata = {
	title: 'Enrollait',
	description: 'Enrollait',
};

export default function SiteLayout({
	children,
}: Readonly<{ children: React.ReactNode }>) {
	return (
		<div className={inter.variable}>
			<div className='min-h-screen bg-[var(--background)] text-[var(--foreground)] antialiased'>
				<Navbar />
				<div className='mx-auto max-w-[1300px] px-2 md:px-4 xl:px-0'>
					{children}

					{/* Footer */}
					<footer className='mb-6 mt-10 flex flex-col gap-4 border-t border-black/5 pt-6 text-xs text-gray-500 sm:flex-row sm:items-center sm:justify-between'>
						<div className='flex items-center gap-2'>
							<span className='grid h-6 w-6 place-items-center rounded bg-[var(--primary)] font-bold text-white'>
								I
							</span>
							<span>© Enrollait. All rights reserved.</span>
						</div>
						<div className='flex items-center gap-6'>
							<button className='hover:text-gray-700'>Privacy Policy</button>
							<button className='hover:text-gray-700'>Terms of Service</button>
							<button className='hover:text-gray-700'>Support</button>
						</div>
					</footer>
				</div>
			</div>
		</div>
	);
}
