import type { Metadata } from 'next';
import { Geist, Geist_Mono, Inter } from 'next/font/google';
import './globals.css';
import Navbar from './components/Navbar';

// const geistSans = Geist({
// 	variable: '--font-geist-sans',
// 	subsets: ['latin'],
// });

// const geistMono = Geist_Mono({
// 	variable: '--font-geist-mono',
// 	subsets: ['latin'],
// });

const inter = Inter({
	variable: '--font-inter',
	subsets: ['latin'],
});

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		// <html lang='en'>
		// 	<body
		// 		className={`${geistSans.variable} ${geistMono.variable} ${inter.variable} antialiased`}
		// 	>
		// 		{children}
		// 	</body>
		// </html>
		<html lang='en'>
			<body className={`${inter.variable} antialiased`}>
				<div className='min-h-screen bg-[var(--background)] text-[var(--foreground)]'>
					<Navbar />
					<div className='mx-auto px-2 md:px-4 xl:px-0 max-w-[1300px]'>
						{children}

						{/* Footer */}
						<div className='mt-10 flex items-center justify-between border-t border-black/5 pt-6 text-xs text-gray-500 mb-6'>
							<div className='flex items-center gap-2'>
								<span className='grid h-6 w-6 place-items-center rounded bg-[var(--primary)] text-white font-bold'>
									I
								</span>
								<span>
									© {new Date().getFullYear()} Enrollait. All rights reserved.
								</span>
							</div>
							<div className='flex items-center gap-6'>
								<button className='hover:text-gray-700'>Privacy Policy</button>
								<button className='hover:text-gray-700'>
									Terms of Service
								</button>
								<button className='hover:text-gray-700'>Support</button>
							</div>
						</div>
					</div>
				</div>
			</body>
		</html>
	);
}
